[package]
name = "wasm_image"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
image = "0.25.2"
svg = "0.17.0"
wasm-bindgen = "0.2.92"


[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Os", "--fast-math"]
