[package]
name = "wasm_yaml"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6.5"

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Os", "--fast-math"]
